/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    steden: Steden;
    locations: Location;
    pois: Pois;
    faq: Faq;
    'faq-categorieen': FaqCategorieen;
    nieuws: Nieuw;
    evenementen: Evenementen;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    steden: StedenSelect<false> | StedenSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    pois: PoisSelect<false> | PoisSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    'faq-categorieen': FaqCategorieenSelect<false> | FaqCategorieenSelect<true>;
    nieuws: NieuwsSelect<false> | NieuwsSelect<true>;
    evenementen: EvenementenSelect<false> | EvenementenSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | UspRijBlock
    | CitaatBlock
    | FaqBlokBlock
    | LocatieUitgelichtBlock
    | KaartenSliderBlock
    | StappenPlanBlock
    | CijfersRijBlock
    | DoelgroepenBlokBlock
    | AppPromoBlokBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * Voor de /zakelijk/{onderwerp} nesting uit docs/IA.md. Informatief voor de breadcrumb; de URL zelf komt uit het slug-veld hieronder (mag een pad met een "/" zijn, bv. "zakelijk/klein-zakelijk-parkeren").
   */
  bovenliggendePagina?: (number | null) | Page;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UspRijBlock".
 */
export interface UspRijBlock {
  items?:
    | {
        titel: string;
        tekst?: string | null;
        icoon?: ('check' | 'clock' | 'shield' | 'car' | 'card' | 'bolt') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'uspRij';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CitaatBlock".
 */
export interface CitaatBlock {
  tekst: string;
  naam?: string | null;
  functie?: string | null;
  foto?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'citaat';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlokBlock".
 */
export interface FaqBlokBlock {
  titel?: string | null;
  bron?: ('alles' | 'categorie' | 'handmatig') | null;
  categorie?: (number | null) | FaqCategorieen;
  vragen?: (number | Faq)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqBlok';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-categorieen".
 */
export interface FaqCategorieen {
  id: number;
  naam: string;
  slug: string;
  volgorde?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('algemeen' | 'betalen' | 'abonnementen' | 'reserveren' | 'zakelijk') | null;
  /**
   * Gebruikt door het FaqBlok op /veelgestelde-vragen en generieke paginas.
   */
  categorie?: (number | null) | FaqCategorieen;
  /**
   * Leeg laten = geldt voor alle locaties
   */
  locations?: (number | Location)[] | null;
  volgorde?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  /**
   * Gebruikt in de URL, bv. parkeren/eindhoven/strijp-s
   */
  slug: string;
  /**
   * Gebruikt door de zoek- en boekingsflow op /parkeren. Nieuw: koppel hieronder ook de Stad-pagina.
   */
  city:
    | 'eindhoven'
    | 'rotterdam'
    | 'amsterdam'
    | 'den-haag'
    | 'utrecht'
    | 'tilburg'
    | 'heerhugowaard'
    | 'zoetermeer'
    | 'almere'
    | 'regio-zuid-holland'
    | 'regio-gelderland';
  /**
   * Koppelt deze locatie aan haar stadspagina (/parkeren/{stad}). Vult de stadssectie en de breadcrumb.
   */
  stad?: (number | null) | Steden;
  address?: {
    street?: string | null;
    huisnummer?: string | null;
    postalCode?: string | null;
    cityName?: string | null;
  };
  /**
   * [lng, lat]
   *
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  /**
   * Het product/locatie-ID zoals gebruikt in de Aeroparker API (koppeling voor beschikbaarheid + prijs)
   */
  aeroparkerProductId: string;
  /**
   * Bv. IP Parking, Skidata, WPS
   */
  leverancier?: string | null;
  googleMapsUrl?: string | null;
  /**
   * In euro, getoond als fallback zolang er geen live Aeroparker-tarief is opgehaald
   */
  pricePerHour: number;
  /**
   * Gemiddelde beoordeling, bv. 4.6. Bron nog te bevestigen, zie docs/CONTENT-MODEL.md.
   */
  rating?: number | null;
  /**
   * Bv. "24/7 geopend" of "06:00 – 01:00"
   */
  openingHours?: string | null;
  /**
   * Bv. "4.50 m (open terrein)"
   */
  maxHeight?: string | null;
  spotsTotal?: number | null;
  /**
   * Handmatig bij te werken vrije plekken, zolang er geen live feed is.
   */
  spotsFree?: number | null;
  /**
   * Gebruikt in listings, de hero en als meta-omschrijving fallback.
   */
  intro?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        image: number | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  amenities?: ('covered' | 'ev-charging' | 'disabled-access' | '24-7' | 'guarded')[] | null;
  /**
   * Terminalregister per locatie, bv. BSG-I1
   */
  terminals?:
    | {
        code: string;
        type?: ('inrit' | 'uitrit' | 'betaal') | null;
        id?: string | null;
      }[]
    | null;
  poiPaginas?: (number | Pois)[] | null;
  faqs?: (number | Faq)[] | null;
  soort?: ('Parkeerterrein' | 'Parkeergarage' | 'Ondergrondse garage' | 'Parkeerdak') | null;
  /**
   * Vrije tekst, bv. "8 min lopen naar centrum"
   */
  loopafstand?: string | null;
  /**
   * Vrije lijst, bv. "Laadpalen (6x)". Vervangt de vaste 'Voorzieningen'-lijst hierboven voor de nieuwe locatiepagina.
   */
  faciliteiten?:
    | {
        tekst: string;
        id?: string | null;
      }[]
    | null;
  betaalmogelijkheden?:
    | {
        tekst: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Vrije tekstlijst voor de 'in de buurt'-sectie. Anders dan de POI-landingspagina's hierboven.
   */
  poisNabij?:
    | {
        naam: string;
        soort?: string | null;
        afstand?: string | null;
        id?: string | null;
      }[]
    | null;
  uren?: {
    open247?: boolean | null;
    doordeweeks?: string | null;
    zaterdag?: string | null;
    zondag?: string | null;
  };
  reserveerbaar?: boolean | null;
  waardekaart?: boolean | null;
  strippenkaart?: boolean | null;
  /**
   * Hoe kom je naar binnen: slagboom, kentekenherkenning, ticket.
   */
  inrit?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  uitrit?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  route?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Gesynchroniseerd: alleen-lezen, wordt elke nacht overschreven door Aeroparker.
   */
  aeroparkerSync?: {
    tarieven?:
      | {
          label: string;
          /**
           * Nederlandse notatie, bv. "12,00"
           */
          prijs: string;
          id?: string | null;
        }[]
      | null;
    dagprijs?: string | null;
    laatsteSync?: string | null;
    syncStatus?: ('ok' | 'verouderd' | 'vermist' | 'fout') | null;
    syncMelding?: string | null;
  };
  /**
   * Sleep om te herordenen, of verwijder een sectie om hem uit te zetten. Elke sectie leest zijn eigen inhoud uit de velden hierboven.
   */
  secties?:
    | (
        | LocatieHeroBlock
        | LocatieTarievenBlock
        | LocatieFaciliteitenBlock
        | LocatieOpeningstijdenBlock
        | LocatiePoisNabijBlock
        | LocatieKaartProductenBlock
        | LocatieEvenementenBlock
        | LocatieFaqBlock
        | ContentBlock
        | CitaatBlock
      )[]
    | null;
  seo?: {
    /**
     * Valt terug op de naam van de locatie.
     */
    titel?: string | null;
    /**
     * Valt terug op de introductietekst.
     */
    omschrijving?: string | null;
    afbeelding?: (number | null) | Media;
    geenIndex?: boolean | null;
  };
  oudeId?: number | null;
  oudeSlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "steden".
 */
export interface Steden {
  id: number;
  naam: string;
  /**
   * Gebruikt in de URL: /parkeren/{url}
   */
  slug: string;
  /**
   * Verandert de H1 van "Parkeren in {naam}" naar "Parkeren in de {naam}"
   */
  isRegio?: boolean | null;
  provincie?: string | null;
  /**
   * Alleen voor het centreren van de kaart, dit is geen locatie.
   *
   * @minItems 2
   * @maxItems 2
   */
  coordinaten?: [number, number] | null;
  /**
   * Sleep om te herordenen. Elke sectie kan uit staan door hem te verwijderen; niets hier is verplicht in een vaste volgorde.
   */
  secties?: (StadHeroBlock | StadLocatiesLijstBlock | ContentBlock | CitaatBlock | CallToActionBlock)[] | null;
  /**
   * Voor het oplossen van cid= redirects.
   */
  oudeCid?: number | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StadHeroBlock".
 */
export interface StadHeroBlock {
  /**
   * Standaard: "Parkeren in {naam van de stad}"
   */
  titel?: string | null;
  intro?: string | null;
  afbeelding?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stadHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StadLocatiesLijstBlock".
 */
export interface StadLocatiesLijstBlock {
  legeMelding?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stadLocatiesLijst';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pois".
 */
export interface Pois {
  id: number;
  name: string;
  /**
   * Standaard: "Parkeren bij {naam}"
   */
  titel?: string | null;
  /**
   * Gebruikt onder /parkeren-bij/{url}
   */
  slug: string;
  category: 'restaurant' | 'shop' | 'hotel' | 'attraction' | 'transit' | 'venue';
  /**
   * Verplicht: dit is wat een POI-pagina onmogelijk een eiland maakt.
   */
  primaireLocatie: number | Location;
  extraLocaties?: (number | Location)[] | null;
  loopafstand?: number | null;
  intro: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinaten?: [number, number] | null;
  address?: string | null;
  image?: (number | null) | Media;
  externalUrl?: string | null;
  secties?: (PoiHeroBlock | ContentBlock | FaqBlokBlock | CitaatBlock)[] | null;
  seo?: {
    titel?: string | null;
    omschrijving?: string | null;
    geenIndex?: boolean | null;
  };
  oudeSlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PoiHeroBlock".
 */
export interface PoiHeroBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'poiHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieHeroBlock".
 */
export interface LocatieHeroBlock {
  reserveerLabel?: string | null;
  /**
   * Bijvoorbeeld de deep link naar Aeroparker voor deze locatie.
   */
  reserveerUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'locatieHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieTarievenBlock".
 */
export interface LocatieTarievenBlock {
  titel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'locatieTarieven';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieFaciliteitenBlock".
 */
export interface LocatieFaciliteitenBlock {
  titel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'locatieFaciliteiten';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieOpeningstijdenBlock".
 */
export interface LocatieOpeningstijdenBlock {
  titel?: string | null;
  telefoon?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'locatieOpeningstijden';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatiePoisNabijBlock".
 */
export interface LocatiePoisNabijBlock {
  titel?: string | null;
  kaartbijschrift?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'locatiePoisNabij';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieKaartProductenBlock".
 */
export interface LocatieKaartProductenBlock {
  titelVoor?: string | null;
  titelNadruk?: string | null;
  titelNa?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'locatieKaartProducten';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieEvenementenBlock".
 */
export interface LocatieEvenementenBlock {
  titelVoor?: string | null;
  titelNadruk?: string | null;
  titelNa?: string | null;
  tekst?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'locatieEvenementen';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieFaqBlock".
 */
export interface LocatieFaqBlock {
  titel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'locatieFaq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieUitgelichtBlock".
 */
export interface LocatieUitgelichtBlock {
  titel?: string | null;
  locatie: number | Location;
  tekst?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'locatieUitgelicht';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KaartenSliderBlock".
 */
export interface KaartenSliderBlock {
  titel?: string | null;
  kaarten?:
    | {
        afbeelding: number | Media;
        titel: string;
        tekst?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'kaartenSlider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StappenPlanBlock".
 */
export interface StappenPlanBlock {
  titel?: string | null;
  stappen?:
    | {
        titel: string;
        tekst?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stappenPlan';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CijfersRijBlock".
 */
export interface CijfersRijBlock {
  cijfers?:
    | {
        waarde: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cijfersRij';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DoelgroepenBlokBlock".
 */
export interface DoelgroepenBlokBlock {
  titel?: string | null;
  groepen?:
    | {
        titel: string;
        tekst?: string | null;
        punten?:
          | {
              tekst: string;
              id?: string | null;
            }[]
          | null;
        link?: {
          label?: string | null;
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'doelgroepenBlok';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AppPromoBlokBlock".
 */
export interface AppPromoBlokBlock {
  titel: string;
  subtitel?: string | null;
  afbeelding?: (number | null) | Media;
  features?:
    | {
        titel: string;
        tekst?: string | null;
        id?: string | null;
      }[]
    | null;
  knoppen?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'appPromo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nieuws".
 */
export interface Nieuw {
  id: number;
  titel: string;
  /**
   * Gebruikt onder /nieuws/{url}
   */
  slug: string;
  publicatiedatum: string;
  auteur?: string | null;
  samenvatting: string;
  inhoud: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  hero?: (number | null) | Media;
  gerelateerdeLocaties?: (number | Location)[] | null;
  gerelateerdeSteden?: (number | Steden)[] | null;
  seo?: {
    titel?: string | null;
    omschrijving?: string | null;
    afbeelding?: (number | null) | Media;
  };
  oudeId?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evenementen".
 */
export interface Evenementen {
  id: number;
  naam: string;
  slug: string;
  /**
   * Bv. Festival of Sport
   */
  soort?: string | null;
  kleur?: ('orange' | 'blue' | 'aqua') | null;
  datums?: string | null;
  afbeelding?: (number | null) | Media;
  vanafPrijs?: string | null;
  locaties: (number | Location)[];
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'steden';
          value: number | Steden;
        } | null)
      | ({
          relationTo: 'locations';
          value: number | Location;
        } | null)
      | ({
          relationTo: 'pois';
          value: number | Pois;
        } | null)
      | ({
          relationTo: 'nieuws';
          value: number | Nieuw;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'steden';
        value: number | Steden;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'pois';
        value: number | Pois;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'faq-categorieen';
        value: number | FaqCategorieen;
      } | null)
    | ({
        relationTo: 'nieuws';
        value: number | Nieuw;
      } | null)
    | ({
        relationTo: 'evenementen';
        value: number | Evenementen;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        uspRij?: T | UspRijBlockSelect<T>;
        citaat?: T | CitaatBlockSelect<T>;
        faqBlok?: T | FaqBlokBlockSelect<T>;
        locatieUitgelicht?: T | LocatieUitgelichtBlockSelect<T>;
        kaartenSlider?: T | KaartenSliderBlockSelect<T>;
        stappenPlan?: T | StappenPlanBlockSelect<T>;
        cijfersRij?: T | CijfersRijBlockSelect<T>;
        doelgroepenBlok?: T | DoelgroepenBlokBlockSelect<T>;
        appPromo?: T | AppPromoBlokBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  bovenliggendePagina?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UspRijBlock_select".
 */
export interface UspRijBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        titel?: T;
        tekst?: T;
        icoon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CitaatBlock_select".
 */
export interface CitaatBlockSelect<T extends boolean = true> {
  tekst?: T;
  naam?: T;
  functie?: T;
  foto?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlokBlock_select".
 */
export interface FaqBlokBlockSelect<T extends boolean = true> {
  titel?: T;
  bron?: T;
  categorie?: T;
  vragen?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieUitgelichtBlock_select".
 */
export interface LocatieUitgelichtBlockSelect<T extends boolean = true> {
  titel?: T;
  locatie?: T;
  tekst?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KaartenSliderBlock_select".
 */
export interface KaartenSliderBlockSelect<T extends boolean = true> {
  titel?: T;
  kaarten?:
    | T
    | {
        afbeelding?: T;
        titel?: T;
        tekst?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StappenPlanBlock_select".
 */
export interface StappenPlanBlockSelect<T extends boolean = true> {
  titel?: T;
  stappen?:
    | T
    | {
        titel?: T;
        tekst?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CijfersRijBlock_select".
 */
export interface CijfersRijBlockSelect<T extends boolean = true> {
  cijfers?:
    | T
    | {
        waarde?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DoelgroepenBlokBlock_select".
 */
export interface DoelgroepenBlokBlockSelect<T extends boolean = true> {
  titel?: T;
  groepen?:
    | T
    | {
        titel?: T;
        tekst?: T;
        punten?:
          | T
          | {
              tekst?: T;
              id?: T;
            };
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AppPromoBlokBlock_select".
 */
export interface AppPromoBlokBlockSelect<T extends boolean = true> {
  titel?: T;
  subtitel?: T;
  afbeelding?: T;
  features?:
    | T
    | {
        titel?: T;
        tekst?: T;
        id?: T;
      };
  knoppen?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "steden_select".
 */
export interface StedenSelect<T extends boolean = true> {
  naam?: T;
  slug?: T;
  isRegio?: T;
  provincie?: T;
  coordinaten?: T;
  secties?:
    | T
    | {
        stadHero?: T | StadHeroBlockSelect<T>;
        stadLocatiesLijst?: T | StadLocatiesLijstBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        citaat?: T | CitaatBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
      };
  oudeCid?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StadHeroBlock_select".
 */
export interface StadHeroBlockSelect<T extends boolean = true> {
  titel?: T;
  intro?: T;
  afbeelding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StadLocatiesLijstBlock_select".
 */
export interface StadLocatiesLijstBlockSelect<T extends boolean = true> {
  legeMelding?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  city?: T;
  stad?: T;
  address?:
    | T
    | {
        street?: T;
        huisnummer?: T;
        postalCode?: T;
        cityName?: T;
      };
  coordinates?: T;
  aeroparkerProductId?: T;
  leverancier?: T;
  googleMapsUrl?: T;
  pricePerHour?: T;
  rating?: T;
  openingHours?: T;
  maxHeight?: T;
  spotsTotal?: T;
  spotsFree?: T;
  intro?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  amenities?: T;
  terminals?:
    | T
    | {
        code?: T;
        type?: T;
        id?: T;
      };
  poiPaginas?: T;
  faqs?: T;
  soort?: T;
  loopafstand?: T;
  faciliteiten?:
    | T
    | {
        tekst?: T;
        id?: T;
      };
  betaalmogelijkheden?:
    | T
    | {
        tekst?: T;
        id?: T;
      };
  poisNabij?:
    | T
    | {
        naam?: T;
        soort?: T;
        afstand?: T;
        id?: T;
      };
  uren?:
    | T
    | {
        open247?: T;
        doordeweeks?: T;
        zaterdag?: T;
        zondag?: T;
      };
  reserveerbaar?: T;
  waardekaart?: T;
  strippenkaart?: T;
  inrit?: T;
  uitrit?: T;
  route?: T;
  aeroparkerSync?:
    | T
    | {
        tarieven?:
          | T
          | {
              label?: T;
              prijs?: T;
              id?: T;
            };
        dagprijs?: T;
        laatsteSync?: T;
        syncStatus?: T;
        syncMelding?: T;
      };
  secties?:
    | T
    | {
        locatieHero?: T | LocatieHeroBlockSelect<T>;
        locatieTarieven?: T | LocatieTarievenBlockSelect<T>;
        locatieFaciliteiten?: T | LocatieFaciliteitenBlockSelect<T>;
        locatieOpeningstijden?: T | LocatieOpeningstijdenBlockSelect<T>;
        locatiePoisNabij?: T | LocatiePoisNabijBlockSelect<T>;
        locatieKaartProducten?: T | LocatieKaartProductenBlockSelect<T>;
        locatieEvenementen?: T | LocatieEvenementenBlockSelect<T>;
        locatieFaq?: T | LocatieFaqBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        citaat?: T | CitaatBlockSelect<T>;
      };
  seo?:
    | T
    | {
        titel?: T;
        omschrijving?: T;
        afbeelding?: T;
        geenIndex?: T;
      };
  oudeId?: T;
  oudeSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieHeroBlock_select".
 */
export interface LocatieHeroBlockSelect<T extends boolean = true> {
  reserveerLabel?: T;
  reserveerUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieTarievenBlock_select".
 */
export interface LocatieTarievenBlockSelect<T extends boolean = true> {
  titel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieFaciliteitenBlock_select".
 */
export interface LocatieFaciliteitenBlockSelect<T extends boolean = true> {
  titel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieOpeningstijdenBlock_select".
 */
export interface LocatieOpeningstijdenBlockSelect<T extends boolean = true> {
  titel?: T;
  telefoon?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatiePoisNabijBlock_select".
 */
export interface LocatiePoisNabijBlockSelect<T extends boolean = true> {
  titel?: T;
  kaartbijschrift?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieKaartProductenBlock_select".
 */
export interface LocatieKaartProductenBlockSelect<T extends boolean = true> {
  titelVoor?: T;
  titelNadruk?: T;
  titelNa?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieEvenementenBlock_select".
 */
export interface LocatieEvenementenBlockSelect<T extends boolean = true> {
  titelVoor?: T;
  titelNadruk?: T;
  titelNa?: T;
  tekst?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocatieFaqBlock_select".
 */
export interface LocatieFaqBlockSelect<T extends boolean = true> {
  titel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pois_select".
 */
export interface PoisSelect<T extends boolean = true> {
  name?: T;
  titel?: T;
  slug?: T;
  category?: T;
  primaireLocatie?: T;
  extraLocaties?: T;
  loopafstand?: T;
  intro?: T;
  coordinaten?: T;
  address?: T;
  image?: T;
  externalUrl?: T;
  secties?:
    | T
    | {
        poiHero?: T | PoiHeroBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        faqBlok?: T | FaqBlokBlockSelect<T>;
        citaat?: T | CitaatBlockSelect<T>;
      };
  seo?:
    | T
    | {
        titel?: T;
        omschrijving?: T;
        geenIndex?: T;
      };
  oudeSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PoiHeroBlock_select".
 */
export interface PoiHeroBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  categorie?: T;
  locations?: T;
  volgorde?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-categorieen_select".
 */
export interface FaqCategorieenSelect<T extends boolean = true> {
  naam?: T;
  slug?: T;
  volgorde?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nieuws_select".
 */
export interface NieuwsSelect<T extends boolean = true> {
  titel?: T;
  slug?: T;
  publicatiedatum?: T;
  auteur?: T;
  samenvatting?: T;
  inhoud?: T;
  hero?: T;
  gerelateerdeLocaties?: T;
  gerelateerdeSteden?: T;
  seo?:
    | T
    | {
        titel?: T;
        omschrijving?: T;
        afbeelding?: T;
      };
  oudeId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evenementen_select".
 */
export interface EvenementenSelect<T extends boolean = true> {
  naam?: T;
  slug?: T;
  soort?: T;
  kleur?: T;
  datums?: T;
  afbeelding?: T;
  vanafPrijs?: T;
  locaties?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}